Numpy python library is a python library is a collection of functions and methods that allows you to perform many actions without writing your code.
For numerical computing , we have numpy library.
For visualization, we have got many libraries like matplotlib.
For data manuplication , we have got pandas.
For machine learning , we have sckit learn.
For deep learning frameworks , we have tensorflow and keras.

The purpose of using this libraries is not to write the entire code from the
beginning.

Numpy stands for numerical python and is the core library for numeric and scientific computing. These methods and functions are part of the numpy library itself.

Numpy:-
It consists of multi-dimensional array objects and a collection of routines for processing those arrays.

In [6]:
import numpy as np
# Single-dimensinal numpy array.
n1 = np.array([10,1])
# Multi -dimensional numpy array.(Lists of Lists , you can create matrix out of it)
n2 = np.array([[10,20,30,40] , [40,30,20,10]]);

print(n1)
print(n2)
 

[10  1]
[[10 20 30 40]
 [40 30 20 10]]


numpy.ndarray

In [7]:
type(n1)
type(n2)


numpy.ndarray

In [10]:
# Initialize Numpy array with zeros 
# zeros(row , columns)
n3 = np.zeros((2,2))
n3

array([[0., 0.],
       [0., 0.]])

In [9]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# Initializing NumPy Array
n5 = np.full((3,3),5)
n5 

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [14]:
n6 = np.full((4,9) , 24)
n6

array([[24, 24, 24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24]])

In [20]:
# Initialize NumPy array with a particular range
n7 = np.arange(10,20)
print(n7)

n8 = np.arange(10,56,2)
print(n8)

[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54]


In [26]:
# Initialize NumPy Array with random numbers.
n9 = np.random.randint(1,100,5);
print(n9)

n10 = np.random.randint(100,1000,10);
print(n10)

[72 20 76 53 68]
[654 291 780 454 370 962 327 676 911 722]


In [32]:
# Checking the shape of the NumPy Array.
# Calling the multidimensional array.
n11 = np.array([[1,2,3],[4,5,6]])
n11.shape
# It will give you the tuple of two parameters (rows, columns)

(2, 3)

In [33]:
n11.shape = (3,2)
n11.shape

(3, 2)

Joining NumPy Arrays.
1] vstack == priority to both rows and columns.(vertical stack two arrays on top of the each other)
2] hstack = priority to row. (horizontally stack two numpy arrays)
3] column_stack = priority to column.
(First numpy array to first column and second numpy array to second column)

In [34]:
n12 = np.array([1,2,3])
n13 = np.array([4,5,6])

np.vstack((n12 , n13))

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
n14 = np.array([40,50,60])
n15 = np.array([10,30,40])

np.hstack((n14,n15))

array([40, 50, 60, 10, 30, 40])

In [36]:
n16 = np.array([60,70,80])
n17 = np.array([90,100,120])

np.column_stack((n16,n17))

array([[ 60,  90],
       [ 70, 100],
       [ 80, 120]])

Numpy Intersection and Difference
Intersection , set difference etc.

In [41]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

print(np.intersect1d(n1,n2))
print(np.setdiff1d(n1,n2))
print(np.setdiff1d(n2,n1))

[50 60]
[10 20 30 40]
[70 80 90]


In [46]:
# Addition of NumPy Arrays
n3 = np.array([1,2])
n4 = np.array([3,4])

np.sum([n3,n4])

np.sum([n3,n4], axis=0)
np.sum([n3 ,n4],axis=1) 

array([3, 7])

In [50]:
n3 = np.array([10, 20])
n4 = np.array([30, 40])

# First element of numpy array1 is added with the first element of numpy array2
print(np.sum([n3,n4],axis=0))
print(np.sum([n3,n4],axis=1))

[40 60]
[30 70]


In [53]:
# Simple Mathematical Operations.
n1 = np.array([10,20,30])
print(n1 + 1)

print(n1*2)

print(n1/2)

print(n1-1)

[11 21 31]
[20 40 60]
[ 5. 10. 15.]
[ 9 19 29]


In [54]:
# Other math functions
n1 = np.array([10,48,23,9,45,61])
# Mean
print(np.mean(n1))

# Standard Deviation
print(np.std(n1))

# Median
print(np.median(n1))

36.666666666666664
19.720265943665385
35.0


Numpy Save and Load

In [55]:
n1 = np.array([10,20,30,40,50,60])
np.save('my_numpy',n1)
# Saving Numpy Array.

In [56]:
n2 = np.load('my_numpy.npy')
# Loading the numpy array.
n2

array([10, 20, 30, 40, 50, 60])